const  DefaultColumns = [
  {
    header: 'FPC Time',
    name: 'FPC_Time',
    code: 'FPC_Time',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
  {
    header: 'Event Name',
    name: 'Event_Name',
    code: 'Event_Name',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
  {
    header: 'FPC_ID',
    name: 'FPC_ID',
    code: 'FPC_ID',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
  {
    header: 'Tel_Time',
    name: 'Tel_Time',
    code: 'Tel_Time',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
  {
    header: 'SeasonNo',
    name: 'SeasonNo',
    code: 'SeasonNo',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
  {
    header: 'EpisodeNo',
    name: 'EpisodeNo',
    code: 'EpisodeNo',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
  {
    header: 'Duration',
    name: 'Duration',
    code: 'Duration',
    width: 'auto',
    ScreenType: 'Song',
    Sequence: 1,
    isvisible: true,
  },
];
export default  DefaultColumns