const enity = [
  {
    category: 'text',
    asterisk: true,
    lable: 'Entity Name',
    placeholder: 'Entity Name',
    name: 'entityname',
    type: 'text',
    width: '50%',
    max: 100,
  },
  {
    category: 'number',
    asterisk: true,
    lable: 'Contact No',
    placeholder: 'Contact',
    name: 'Contact',
    type: 'number',
    width: '50%',
  },
  {
    category: 'Address',
    asterisk: true,
    lable: 'Permanent Address',
    placeholder: 'Permanent Address',
    name: 'PermAddress',
    type: 'text',
    width: '100%',
  },
  {
    category: 'Address',
    asterisk: true,
    lable: 'Corporate Address',
    placeholder: 'Corporate Address',
    name: 'CorpAddress',
    type: 'text',
    width: '100%',
  },
  {
    category: 'ContactPerson',
    asterisk: true,
    lable: 'Contact Person',
    placeholder: 'Contact Person',
    name: 'ContactPerson',
    type: 'text',
    width: '50%',
  },
  {
    category: 'pan',
    asterisk: true,
    lable: 'PAN No.',
    placeholder: 'PAN No.',
    name: 'PANNO',
    type: 'text',
    width: '50%',
    max: 10,
  },
  {
    category: 'text',
    asterisk: false,
    lable: 'CIN No.',
    placeholder: 'CIN No.',
    name: 'CINNumber',
    type: 'text',
    width: '50%',
  },
  {
    category: 'Status',
    asterisk: true,
    lable: 'Status',
    name: 'IsActive',
    width: '50%',
  },
];
export default enity;
