import { reportsEnum } from '../enums/ReportsEnums';

const barcComparisonReport = {
  inputs: [
    {
      type: reportsEnum.inputType.select,
      label: 'Week',
      required: true,
      options: [
        { value: '28', label: 'Week 28' },
        { value: '29', label: 'Week 29' },
        { value: '30', label: 'Week 31' },
        { value: '31', label: 'Week 31' },
        { value: '32', label: 'Week 32' }
      ],
      stateKey: 'week',
    },
    {
      type: reportsEnum.inputType.select,
      label: 'Channel 1',
      required: true,
      options: [
        { value: 'PTC_Punjabi', label: 'PTC Punjabi' },
        { value: 'PTC_Chak_De', label: 'PTC Chak De' },
        { value: 'PTC_Music_v', label: 'PTC Music' },
        { value: 'PTC_Simran_v', label: 'PTC Simran' },
        { value: 'PTC_News', label: 'PTC News' },
        { value: 'PTC_Punjabi_Gold_v', label: 'PTC Punjabi Gold' },

      ],
      stateKey: 'flag',
    },
    {
      type: reportsEnum.inputType.multiSelect,
      label: 'Channel 2',
      required: true,
      size: 'sm',
      options: [
        { value: 'Zee_Punjabi', label: 'Zee Punjabi' },
        { value: 'DD_Punjabi', label: 'DD Punjabi' },
        { value: 'Chardikla_Time_TV', label: 'Chardikla Time TV' },
        { value: 'MH_One', label: 'MH One' },
        { value: '9X_Tashan', label: '9X Tashan' },
        { value: 'Balle_Balle', label: 'Balle Balle' },
        { value: 'Punjabi_Hits', label: 'Punjabi Hits' },
        { value: 'News18_PH', label: 'News18 PH' },
        { value: 'Living_India_News', label: 'Living India News' },
        { value: 'MH_One_News', label: 'MH One News' },
        { value: 'Zee_Punjab_HH', label: 'Zee Punjab HH' },
        { value: 'Pitaara_TV', label: 'Pitaara TV' },
        { value: 'Manoranjan_Movies', label: 'Manoranjan Movies' },
        { value: 'Tabbar_Hits', label: 'Tabbar Hits' },
        { value: 'Daily_Post', label: 'Daily Post' },
        { value: 'WPN_World_Punjabi', label: 'WPN World Punjabi' },
        { value: 'News_State_PHH', label: 'News State PHH' },
        { value: 'STAR_Utsav', label: 'STAR Utsav' },
        { value: 'Goldmines', label: 'Goldmines' },
        { value: 'STAR_Plus', label: 'STAR Plus' },
        { value: 'Dangal', label: 'Dangal' },
        { value: 'Sony_Pal', label: 'Sony Pal' },
        { value: 'Anmol_TV', label: 'Anmol TV' },
        { value: 'SONY_SAB', label: 'SONY SAB' },
        { value: 'Colors', label: 'Colors' },
        { value: 'Colors_Rishtey', label: 'Colors Rishtey' },
        { value: 'Zee_TV', label: 'Zee TV' },
        { value: 'Sony_Entertainment_Television', label: 'Sony Entertainment Television' },
        { value: 'B4U_Movies', label: 'B4U Movies' },
        { value: 'Anmol_Cinema', label: 'Anmol Cinema' },
        { value: 'Dangal_2', label: 'Dangal 2' },
        { value: 'STAR_Utsav_Movies', label: 'STAR Utsav Movies' },
        { value: 'Goldmines_Bollywood', label: 'Goldmines Bollywood' },
        { value: 'Colors_Cineplex_Bollywood', label: 'Colors Cineplex Bollywood' },
        { value: 'Manoranjan_TV', label: 'Manoranjan TV' },
        { value: 'B4U_Kadak', label: 'B4U Kadak' },
        { value: 'Shemaroo_TV', label: 'Shemaroo TV' },
        { value: 'Sony_Wah', label: 'Sony Wah' },
        { value: 'MH_One_Dil_Se', label: 'MH One Dil Se' },
        { value: 'Manoranjan_Grand', label: 'Manoranjan Grand' },
        { value: 'Zee_Action', label: 'Zee Action' },
        { value: 'Goldmines_Movies', label: 'Goldmines Movies' },
        { value: 'Manoranjan_Prime', label: 'Manoranjan Prime' },
        { value: 'NICK(v)', label: 'NICK(v)' },
        { value: 'Disney_Channel(v)', label: 'Disney Channel(v)' },
        { value: 'Zee_Cinema', label: 'Zee Cinema' },
        { value: 'STAR_Gold', label: 'STAR Gold' },
        { value: 'Sony_MAX(v)', label: 'Sony MAX(v)' },
        { value: 'ABP_News', label: 'ABP News' },
        { value: 'Aaj_Tak', label: 'Aaj Tak' },
        { value: 'India_TV', label: 'India TV' },
        { value: 'News18_India', label: 'News18 India' },
        { value: 'Zee_News', label: 'Zee News' },
        { value: 'Republic_Bharat', label: 'Republic Bharat' },
        { value: 'TV9_Bharatvarsh', label: 'TV9 Bharatvarsh' },
        { value: 'News_Nation', label: 'News Nation' },
        { value: 'News_24', label: 'News 24' },
        { value: 'Good_News_Today', label: 'Good News Today' },
        { value: 'Zee_Bharat', label: 'Zee Bharat' },
        { value: 'DD_News', label: 'DD News' },
        { value: 'India_News(na)', label: 'India News(na)' },
        { value: 'Times_Now_Navbharat', label: 'Times Now Navbharat' },
        { value: 'NDTV_India', label: 'NDTV India' }
      ],
      stateKey: 'entities',
    },
  ],
  report: {
    fetchType: reportsEnum.fetchType.sp,
    fetchUrl: 'USP_BARCCompareReport',
    params: [
      {
        param: 'Week',
        type: 'state',
        stateKey: 'week',
        inputType: reportsEnum.inputType.select,
      },
      {
        param: 'Channel',
        type: 'state',
        stateKey: 'flag',
        inputType: reportsEnum.inputType.select,
      },
      {
        param: 'MultiChannel',
        type: 'state',
        stateKey: 'entities',
        inputType: reportsEnum.inputType.multiSelect,
      },
    ],
  },
};

export default barcComparisonReport;
